#!/bin/bash
  
#PBS -l ncpus=10
##PBS -l ngpus=2
##PBS -q gpuvolta
#PBS -q hugemem
##PBS -q express
#PBS -P yf70
#PBS -l wd
#PBS -l walltime=24:00:00
#PBS -l mem=200GB
#PBS -l jobfs=1GB
#PBS -l storage=scratch/yf70/ra7413/spacy+gdata/yf70


##PBS -m abe
#PBS -M rana-salal.ali@students.mq.edu.au

source /g/data/yf70/miniconda3/envs/spacy3/bin/activate
cd /scratch/yf70/ra7413/spacy_mi

python spacy3_mi_full_dataset_MI_attack.py --label $label --model 'en_core_web_lg' --epoch $epoch --drop 0.4 --beam_width 3 --subruns $subruns --batch_size $batch_size --attack_type $attack_type --dataset $dataset --member_set $member_set --non_member_set $non_member_set --test_set $test_set

#python spacy3_mi_full_dataset_MI_attack.py --label "ID" --model 'en_core_web_lg' --epoch 75 --drop 0.4 --beam_width 3 --subruns 1 --batch_size 50 --attack_type MIA --dataset dataset/i2b2_n2c2_train_data.pickle --member_set dataset/i2b2_n2c2_member_sentences.pickle --non_member_set dataset/i2b2_n2c2_non_member_sentences.pickle
