#!/bin/bash
  
for (( i = 1; i <= 10000; i=i+1000 ))
do
        #echo $i
        for (( r = 1 ; r <= 10; r++ ))
        do
                #echo $r
                qsub -v insertions=$i,run=$r jobscript;
        done
done